In [2]:
import pandas as pd
import numpy as np

trying to find what could be merged, removing collumns that make no sense

In [3]:
objects = pd.read_csv("./raw_data/objects.csv")
relationships = pd.read_csv("./raw_data/relationships.csv")
people = pd.read_csv("./raw_data/people.csv")
funding_rounds = pd.read_csv("./raw_data/funding_rounds.csv")
ipos = pd.read_csv("./raw_data/ipos.csv")
investments = pd.read_csv("./raw_data/investments.csv")
funds = pd.read_csv("./raw_data/funds.csv")
degrees = pd.read_csv("./raw_data/degrees.csv")
acquisitions = pd.read_csv("./raw_data/acquisitions.csv")

/var/folders/6g/_ldjv_pd0k36jp2tc2jnbcl00000gn/T/ipykernel_47300/3290259358.py:1: DtypeWarning: Columns (3,7,9,10,17,18,21,22,23,25,26,29,30,37) have mixed types. Specify dtype option on import or set low_memory=False.
  objects = pd.read_csv("./raw_data/objects.csv")

In [4]:
# offices = pd.read_csv("./raw_data/offices.csv", nrows=100)
# # offices.to_csv('./raw_data/new_offices.csv', index=False)

# products = objects[objects['id'].str.contains('r', na=False)]

# unique_letters = {char for id_val in objects['id'].dropna().astype(str) for char in id_val if char.isalpha()}

# # Convert the set to a sorted list
# unique_letters_list = sorted(list(unique_letters))
# print(unique_letters)

In [19]:
objects_collumns = objects.drop(['entity_id','normalized_name', 'permalink', 'homepage_url', 'logo_url', 'logo_width', 'logo_height', 'state_code', 'created_by', 'first_milestone_at', 'last_milestone_at', 'milestones'], axis=1)
relationships_collumns = relationships.drop(['id', 'relationship_id', 'sequence','created_at', 'updated_at'], axis=1)
people_collumns = people.drop(['id', 'birthplace'], axis=1)
funding_rounds_collumns = funding_rounds.drop(['id','pre_money_valuation', 'pre_money_currency_code', 'post_money_valuation', 'post_money_currency_code', 'source_url', 'source_description', 'created_by', 'created_at', 'updated_at'], axis=1)
ipos_collumns = ipos.drop(['id','ipo_id', 'source_url', 'source_description', 'created_at', 'updated_at'], axis=1)
investments_collumns = investments.drop(['id', 'created_at', 'updated_at'], axis=1)
funds_collumns = funds.drop(['id', 'fund_id', 'source_url', 'source_description', 'created_at', 'updated_at'], axis=1)
degrees_collumns = degrees.drop(['id', 'created_at', 'updated_at'], axis=1)
acquisitions_collumns = acquisitions.drop(['id', 'source_url', 'source_description', 'created_at', 'updated_at'], axis=1)
# offices_collumns = offices.drop(['id','description', 'office_id', 'address1', 'address2', 'zip_code', 'state_code', 'latitude', 'longitude', 'created_at', 'updated_at'], axis=1)

In [20]:
people_degrees = pd.merge(people_collumns, degrees_collumns, left_on = 'object_id', right_on = 'object_id', how = 'left')
investments_funds = pd.merge(investments_collumns, funds_collumns, left_on = 'investor_object_id', right_on = 'object_id', how = 'left')
investments_funds_collumn = investments_funds.drop(['object_id'], axis=1)
objects_offices = pd.merge(objects_collumns, offices_collumns, left_on = 'id', right_on = 'object_id', how = 'left')
relationships_people = pd.merge(relationships_collumns, people_degrees, left_on = 'person_object_id', right_on = 'object_id', how = 'left')
relationships_people_collumn = relationships_people.drop(['object_id'], axis=1)

In [24]:
objects_collumns.to_csv('./raw_data/new_obj.csv', index=False)
relationships_collumns.to_csv('./raw_data/new_relationships.csv', index=False)
people_collumns.to_csv('./raw_data/new_people.csv', index=False)
funding_rounds_collumns.to_csv('./raw_data/new_funding_rounds.csv', index=False)
ipos_collumns.to_csv('./raw_data/new_ipos.csv', index=False)
investments_collumns.to_csv('./raw_data/new_investments.csv', index=False)
funds_collumns.to_csv('./raw_data/new_funds.csv', index=False)
degrees_collumns.to_csv('./raw_data/new_degrees.csv', index=False)
acquisitions_collumns.to_csv('./raw_data/new_acquisitions.csv', index=False)
objects_offices.to_csv('./raw_data/new_objects_offices.csv', index=False)

In [25]:


people_degrees.to_csv('./raw_data/new_people_degrees.csv', index=False)
investments_funds_collumn.to_csv('./raw_data/new_investments_funds.csv', index=False)
relationships_people.to_csv('./raw_data/new_relationships_people.csv', index=False)
relationships_people_collumn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 565213 entries, 0 to 565212
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   person_object_id        565213 non-null  object
 1   relationship_object_id  565213 non-null  object
 2   start_at                302772 non-null  object
 3   end_at                  160773 non-null  object
 4   is_past                 565213 non-null  int64
 5   title                   548003 non-null  object
 6   first_name              564288 non-null  object
 7   last_name               564290 non-null  object
 8   affiliation_name        564215 non-null  object
 9   degree_type             359171 non-null  object
 10  subject                 298485 non-null  object
 11  institution             390740 non-null  object
 12  graduated_at            219418 non-null  object
dtypes: int64(1), object(12)
memory usage: 56.1+ MB

In [15]:
people_degrees = pd.read_csv('./raw_data/people_degrees.csv', nrows=1000)
investments_funds_collumn = pd.read_csv('./raw_data/investments_funds.csv', nrows=1000)
relationships_people = pd.read_csv('./raw_data/relationships_people.csv', nrows=1000)
objobj = pd.read_csv('./raw_data/objects_offices.csv', nrows=1000)

objobj.to_csv('./raw_data/objects_offices.csv', index=False)
people_degrees.to_csv('./raw_data/new_people_degrees.csv', index=False)
investments_funds_collumn.to_csv('./raw_data/new_investments_funds_collumn.csv', index=False)
relationships_people.to_csv('./raw_data/new_relationships_people.csv', index=False)

In [16]:
people_relationships_cleaned = relationships_people_collumn.drop_duplicates(subset=['title', 'first_name', 'last_name', 'affiliation_name', 'degree_type'], keep='last')
people_relationships_cleaned.info()
people_relationships_cleaned.to_csv('./raw_data/people_relationships_cleaned.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
Index: 484422 entries, 1 to 565212
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   person_object_id        484422 non-null  object
 1   relationship_object_id  484422 non-null  object
 2   start_at                264163 non-null  object
 3   end_at                  140684 non-null  object
 4   is_past                 484422 non-null  int64
 5   title                   471419 non-null  object
 6   first_name              484077 non-null  object
 7   last_name               484079 non-null  object
 8   affiliation_name        484010 non-null  object
 9   degree_type             296120 non-null  object
 10  subject                 245499 non-null  object
 11  institution             318637 non-null  object
 12  graduated_at            180123 non-null  object
dtypes: int64(1), object(12)
memory usage: 51.7+ MB

In [4]:
objects_collumns = objects.drop(['relationships', 'entity_id','normalized_name', 'permalink', 'logo_url', 'logo_width', 'logo_height', 'state_code', 'created_by', 'first_milestone_at', 'last_milestone_at', 'milestones'], axis=1)

products = objects_collumns[objects_collumns['id'].str.contains('r', na=False)]
companies = objects_collumns[objects_collumns['id'].str.contains('c', na=False)]
people_from_obj = objects_collumns[objects_collumns['id'].str.contains('p', na=False)]
financial_org = objects_collumns[objects_collumns['id'].str.contains('f', na=False)]

products.to_csv('./raw_data/new_products.csv', index=False)
companies.to_csv('./raw_data/new_companies.csv', index=False)
people_from_obj.to_csv('./raw_data/new_people_from_obj.csv', index=False)
financial_org.to_csv('./raw_data/new_financial_org.csv', index=False)